archives:
    - replacements:
        "386": i386
        amd64: x86_64
        darwin: Darwin
        linux: Linux
        windows: Windows
before:
    hooks:
        - go mod tidy
        - go generate ./...
builds:
    - env:
        - CGO_ENABLED=0
      goos:
        - linux
        - windows
        - darwin
      id: cfctl
      main: ./cmd/cfctl
      binary: cfctl
changelog:
    filters:
        exclude:
            - '^docs:'
            - '^test:'
    sort: asc
checksum:
    name_template: checksums.txt
snapshot:
    name_template: '{{ incpatch .Version }}-next'
